### ISSUE TITLE
emphasise fsspec

### ISSUE THREAD

**Issue by martindurant** [fsspec/dropboxdrivefs#1]
I would change the README language, to say that this is an implementation of dropbox acces for fsspec, and refer to its documentation first. Only after that would I refer to Intake - that happens to be your use case, but there may be many others out there who use it directly or via dask.

Note that the readme at https://pypi.org/project/dropboxdrivefs/ does not to be the current one on this repo, and doesn't render very well. You need to set the formatting to markdown (assumes RST by default). Also, the bash install commands are not useful for windows users.

**Comment by MarineChap** [comment]
Thanks you. I add this new version in local and I just forget about it and never pushed it. 
And I did not know for the markdown formatting. I will do it, right now. 

By the way, for the moment I don't success to use intake/xarray with the dropbox implementation. I need to find the problem but I don't have the time right now. So, for the moment I removed mention of intake in the readme.
