### ISSUE TITLE
withdirs param not working w/ find

### ISSUE THREAD

**Issue by dv-rastogi** [fsspec/dropboxdrivefs#10]
Hi!
Referencing the [find](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem.find) function of abstract file system, it has a param `withdirs`. Although irrespective of the value of `withdirs`, the dropboxdrivefs `find` function always seems to return a list including directories.

Just documenting the issue for now, no immediate fix is required.

**Comment by MarineChap** [comment]
Dear, sorry for the delay. 

Looks like it is fixed now. I added the example in the notebook. 
If you see I misunderstood or you still have the issue on your side, please tell me which package/version of fsspec you are using in background. 

I will close it for now. Thank you for your reporting.
