### ISSUE TITLE
`ls()` deviates from other fsspec implementations

### ISSUE THREAD

**Issue by chandrasekharan98** [fsspec/dropboxdrivefs#12]
Hello
I'm trying to make use of multiple fsspec implementations and currently I've used [s3fs](https://s3fs.readthedocs.io/en/latest/) and [HTTP(S)](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.implementations.http.HTTPFileSystem). Comparing `ls()` from these 3 implementations - I noticed that dropboxdrivefs recursively lists the subdirectories as well which doesn't seem to be the case in other implementations.

Versions used:
`dropboxdrivefs==1.3.1`
`fsspec==2023.6.0` (for HTTP(S))
`s3fs==2023.6.0`

Looking into the [code](https://github.com/fsspec/dropboxdrivefs/blob/master/dropboxdrivefs/core.py#L58), I see that by default we set `recursive=True` and this isn't configurable either. Can we set it to `False` by default to ensure its in sync with the other fsspec implementations? (might be a breaking change but I feel that its necessary to stay in sync with fsspec). It would be nice if its configurable too to ensure others aren't entirely impacted by this.

Thanks in advance! :)

**Comment by MarineChap** [comment]
Sorry, I missed your issue ! You are entirely right. I will do the update and it will be part of the release I can do once issue #13 is done too. 

Thank you for your suggestion.

**Comment by MarineChap** [comment]
By the way, I saw you published it on pypi with your name. 
For a so small modification, you could have first open a PR for me and second avoid removing my name from the author list to put yours when you built your version.

**Comment by chandrasekharan98** [comment]
@MarineChap thank you for the fix you've made. My bad on not checking with you earlier regarding this fix, however I had to publish the fix to PyPI to refer from in one of our dependent packages. Raising a PR to your repo was in my TODOs but I lost track of it amidst other priorities.
We'll be able to take it down from PyPI once your fix is released to PyPI.

**Comment by chandrasekharan98** [comment]
@MarineChap do you have any ETA for the next release which can contain this fix? We'll be happy to update our dependencies to use your package once its released. Post which we can safely remove our patched version from PyPI.
Thank you :)

**Comment by MarineChap** [comment]
@chandrasekharan98  Hello, sorry I was waiting on the copy PR. 
There is a new release online 1.4.0
Have a good day.

**Comment by chandrasekharan98** [comment]
@MarineChap thank you for releasing the fix. We've taken down the other library that we had published to PyPI as well.
