### ISSUE TITLE
How do I create a token?

### ISSUE THREAD

**Issue by rabernat** [fsspec/dropboxdrivefs#2]
I would like to try to use this package. But I could not figure out from the documentation how to create the required token. It would be great to have this the documentation. Thanks!

**Comment by MarineChap** [comment]
Hello! 

You need to be connected on your dropbox account and go in the [developers/apps dropbox page](https://www.dropbox.com/developers/apps). Then, you can add a new app, give it full access or just a folder and generate the token. 
I am sure you already know about that but be careful not to write in plain text your token, neither store it in a git account. You can add it in a config file and upload from it in your python code. 

Thank you for your issue ! :) I will add this in the readme documentation.

**Comment by rabernat** [comment]
Thanks a lot for your quick reply! It worked!
