### ISSUE TITLE
Get modified time of file/folder

### ISSUE THREAD

**Issue by dv-rastogi** [fsspec/dropboxdrivefs#7]
Hi!
Currently, there is no implementation for the `modified` method of `AbstractFileSystem` in dropbox. Also, the `info` method doesn't return the modified time metadata. Although upon printing the metadata inside the library code (Inside `core.py`):
```python
def info(self, url, **kwargs):
        """Get info of URL
        """
        metadata = self.dbx.files_get_metadata(url)
        print(metadata) # my print statement
        return self._refactor_metadata(metadata)
```
I am able to see the modified time as a datetime object; the method  `_refactor_metadata` happens to remove it in the final output for `info`. 
What's the reason for the same? Could fetching `modified` attribute for files/folder be incorporated as a functionality?

**Comment by MarineChap** [comment]
Hello, 
No particular reason other than at this time I was following the fsspec template asking for this keys in the return dictionary 
- name (full path in the FS), 
- size (in bytes)
- type (file...)

So I don't see a reason not to add all the other metadata. Do you want to do a PR for it? Or as it is small I should be okay by adding it this weekend. 
Thank for the feedback. Have a good day

**Comment by dv-rastogi** [comment]
Hey @MarineChap, Thanks for your reply and the opportunity to contribute! :)
Although I am jammed up with work right now and have less clue about other metadata apart from my use case (i.e. `modified_time`), hence would have to pass on this contribution. 

Looking forward to possible future contributions! :)
Thanks a mil!

**Comment by MarineChap** [comment]
Hello, sorry I have been myself overload with work. 
But I am not forgetting you. I will push the modif soon.

**Comment by MarineChap** [comment]
Done. The release will follow but I want to add first a test/release pipeline instead of doing manually, so no promise when exactly it will follow. 

Don't hesitate to open other issues if you find some other missing use-cases you would like to add. 
Thanks, Have a good week.
