### ISSUE TITLE
Faulty walk

### ISSUE THREAD

**Issue by dv-rastogi** [fsspec/dropboxdrivefs#9]
Hi!
This is referencing the `walk` functionality of fsspec abstract filesystem ([ref](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem.walk)).

Currently, I have the following folder structure: 
```
A/
| - A1.txt
| - B/
| - - B1.txt
```

I get the following result with `walk("/A")`:
```
[('/A', ['B'], ['', 'B1.txt', 'A1.txt']), ('/A/B', [], ['', 'B1.txt'])]
```
which is incorrect. It seems to list all of the files within a folder, but it should only list the files on the same level.

**Comment by MarineChap** [comment]
Hello, 
I am not clear on the exact output you wanted. If I follow the ref you gave, it say "List all files, recursing into subdirectories"
So, that's seem to follow the spec.  

Can you re-explain me your issue please ? 
Thanks, Have a good day

**Comment by dv-rastogi** [comment]
So as per the spec, it should replicate how the output of os.walk, so the intended output should be 
```
[('A', ['B'], ['A1.txt']), ('A/B', [], ['B1.txt'])]
```
Here, an entry `(X, Y, Z)` in the output is as the following: In the folder `X`, sub-folders **just** inside the folder `X` forms the list `Y`, and files **just** inside the folder `X` forms the list `Z`. 
Here **just** implies not recursing into subdirectories of `X`.

But the current output is as the following
```
[('/A', ['B'], ['', 'B1.txt', 'A1.txt']), ('/A/B', [], ['', 'B1.txt'])]
```
Here, an entry `(X, Y, Z)` in the output is as the following: In the folder `X`, **all** of the sub-folders inside the folder `X` forms the list `Y`, and **all** of the files inside the folder `X` forms the list `Z`. 
Here **all** implies the recursing into subdirectories of `X`.

I hope this clears up the confusion.

**Comment by MarineChap** [comment]
Ah yes indeed I see what you mean. 
Through I don't see a quick fix... Probably linked to the ls returned output. Do you already have a fix in mind ? 

I am actually not available to work on it before mid-july as I have a new baby at home :) 

Thanks for reporting the bug.

**Comment by dv-rastogi** [comment]
I don't have a straightaway fix for the issue. Although, the delay is fine! And congratulations! :)

**Comment by MarineChap** [comment]
Looks like it has been fixed (probably via the fsspec repository). 
I added an example in the notebook if you want to verify it. 

I am closing it for now;
